### ISSUE TITLE
Email notification links fail if not already logged in.

### ISSUE THREAD

**Issue by hackademix** [loristissino/Yelloworkflow#1]
If you follow the "Resoconto di cassa - [month] [year]" link sent with the YWF Bot notification (e.g. https://ywf.uaar.it/index.php/periodical-report-submissions/view?id=218 ) and you're not logged in yet, you get stuck on a blank page which should apparently redirect you to the actual destination after choosing the organizational unit, but no way to do it is offered:

https://ywf.uaar.it/index.php/site/choose-organizational-unit?return=%2Findex.php%2Fperiodical-report-submissions%2Fview%3Fid%3D218

Expected result: you should just be asked to log in and, after being successfully authenticated and authorized, automatically redirected to the destination page.

If you're already logged in the link worked as expected.

**Comment by loristissino** [comment]
Thanks for opening the issue. Should be fixed now.
